### PR TITLE
Fixing the audit instance configuration - using inmemory persistence

### PR DESCRIPTION
**Pull request by tmasternak**
Audit Instance should be using the persister that is provided in the nuget package i.e. in-memory peristence.

### CODE REVIEW

**Comment by andreasohlund** [comment]
@mikeminutillo @mauroservienti didn't we intend to use Raven3.5 to make sure changes where persister across restarts?

Not against using the in-memory persister tho

**Comment by tmasternak** [comment]
@andreasohlund this is triggered me to think that we wanted InMemory:

https://github.com/Particular/ServiceControl/blob/master/src/Particular.PlatformSample.ServiceControl/Particular.PlatformSample.ServiceControl.csproj#L29

**Comment by mauroservienti** [comment]
> @mikeminutillo @mauroservienti didn't we intend to use Raven3.5 to make sure changes are persisted across restarts?
> 
> Not against using the in-memory persister tho

Me neither. However, I think it makes sense to keep it on RavenDB 3.5 to provide a better experience when restarting the solution.

**Comment by andreasohlund** [comment]
>https://github.com/Particular/ServiceControl/blob/master/src/Particular.PlatformSample.ServiceControl/Particular.PlatformSample.ServiceControl.csproj#L29

I think that was a misstake but perhaps its a pointer from the IT-gods that we should switch?

**Comment by dvdstelt** [comment]
> Me neither. However, I think it makes sense to keep it on RavenDB 3.5 to provide a better experience when restarting the solution.

For me a better experience would be to restart and start with a clean slate. Hate it when I boot up a demo after a month and see there are still failed messages in SC/SP

**Comment by mauroservienti** [comment]
> > Me neither. However, I think it makes sense to keep it on RavenDB 3.5 to provide a better experience when restarting the solution.
> 
> For me a better experience would be to restart and start with a clean slate. Hate it when I boot up a demo after a month and see there are still failed messages in SC/SP

Yes, I share the same feeling. However, it's a different use case. Users might start debugging a solution that includes the Platform sample. A message fails, they stop the debugger, fix the problem, and want to retry the previously failed message.. But it's gone.

**Comment by bording** [comment]
> > https://github.com/Particular/ServiceControl/blob/master/src/Particular.PlatformSample.ServiceControl/Particular.PlatformSample.ServiceControl.csproj#L29
> 
> I think that was a misstake but perhaps its a pointer from the IT-gods that we should switch?

It wasn't a mistake. I intentionally changed that when I moved over to the artifact definition format. I agree with @dvdstelt that it doesn't make sense to care about persistent data for this demo/sample package.

I didn't realize that there was a follow-up change needed here, or I would have made it at the same time.

**Comment by tmasternak** [comment]
> For me a better experience would be to restart and start with a clean slate. Hate it when I boot up a demo after a month and see there are still failed messages in SC/SP

Right now the PlatfromSample runs the main instance with RavenDB35 and the audit with InMemory store. The behavior is inconsistent and we can't run the main instance with InMemory.

**Comment by mikeminutillo** [comment]
The intention was to eventually switch everything to in memory once it's all available. It might require a review of the existing samples and tutorials to ensure they aren't relying on the persistent behavior.

**Comment by tmasternak** [comment]
We've talked with @bording and the context of the original changes was:
* The package with `InMemory` is significantly smaller than with `RavenDB35` storage
* We should soon be able to do the same for the main instance

Consider ☝️ @jpalac and I decided to stick with `InMemory` storage.

**Review by jpalac — APPROVED** [review]

**Comment by mauroservienti** [comment]
For the record, I cannot disagree more with this change. Not to mention that my point of view was ignored.

**Comment by tmasternak** [comment]
@mauroservienti I am sorry for not addressing your input - should have done better. The rationale behind merging this PR was "let's keep things as they are and fix the demo so that it works as intended".

I got confused by comments from you and @andreasohlund and assumed that the change was done when you worked on providing RavenDB5 storage for ServiceControl. When we realized that is not the case we went with "let's keep things as they are".

I was trying to figure out when was the decision made to switch to `InMemory` storage but was not able to connect the dots. @bording @dvdstelt do you have more context on that?

**Comment by DavidBoike** [comment]
If you scroll to the end of https://docs.particular.net/tutorials/quickstart/tutorial-reliability, search for "Armed with this information", and read the numbered list directly below that, you'll see that the tutorials absolutely do rely on persistent data between runs of the platform sample.

In this case that's recoverability and not auditing, but persistent storage IS a thing we need to do.

And this viewpoint:

> For me a better experience would be to restart and start with a clean slate.

The platform sample is designed for users running a new sample they just downloaded. **It is not designed for us**.

**Pull request merged**
