### PR TITLE
Bumping the netfw dependency to 4.6.2 because of Sc update

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by danielmarbach** [comment]
Once this is released we need to check which docs samples require updates

**Comment by danielmarbach** [comment]
@DavidBoike do you happen to know which samples require an update by any chance? If not I'll do the research

**Comment by DavidBoike** [comment]
I don't have any better knowledge than you'd get from a search.

**Comment by danielmarbach** [comment]
Found them https://github.com/Particular/docs.particular.net/pull/4747

**Pull request merged**
